from fpdf import FPDF
from datetime import datetime

def export_chat_pdf(chat_history, filename="Healora_Report.pdf"):
    pdf = FPDF()
    pdf.add_page()

    # Title
    pdf.set_font("Arial", "B", 16)
    pdf.cell(0, 10, "Healora - AI Medical Assistant", ln=True)

    # Date
    pdf.set_font("Arial", size=10)
    pdf.cell(
        0,
        8,
        f"Generated on: {datetime.now().strftime('%d %b %Y, %H:%M')}",
        ln=True
    )

    pdf.ln(5)

    # Disclaimer
    pdf.set_font("Arial", "I", 10)
    pdf.multi_cell(
        0,
        6,
        "Disclaimer: This report is generated by an AI-based medical assistant "
        "and is intended for informational purposes only. "
        "It does not provide medical diagnosis or treatment."
    )

    pdf.ln(8)

    # Chat content
    pdf.set_font("Arial", size=12)
    for line in chat_history:
        pdf.multi_cell(0, 8, line)
        pdf.ln(1)

    pdf.output(filename)
    return filename
